DROP TABLE IF EXISTS AudioTextAssociation;
DROP TABLE IF EXISTS AudioData;
DROP TABLE IF EXISTS TextData;

CREATE TABLE AudioData (
    AudioID INT PRIMARY KEY,
    AudioContent BLOB,
    UploadTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TextData (
    TextID INT PRIMARY KEY,
    TextContent BLOB,
);

CREATE TABLE AudioTextAssociation (
    AudioID INT,
    TextID INT,
    UploadTime TIMESTAMP,
    ConversionTime TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (AudioID) REFERENCES AudioData(AudioID) ON DELETE CASCADE,
    FOREIGN KEY (TextID) REFERENCES TextData(TextID) ON DELETE CASCADE
);